repo_url: https://github.com/Requisitos-de-Software/2024.1-Meu-INSS
repo_name: 2024.1-Meu-INSS
site_url: https://github.com/Requisitos-de-Software/2024.1-Meu-INSS

site_name: Meu INSS
nav:
    - Início: "index.md"
    - Apresentação: 
        - Apresentação 1: "apresentacao/apresentacao01.md"
        - Apresentação 2: "apresentacao/apresentacao02.md"
        - Apresentação 3: "apresentacao/apresentacao03.md"
        - Apresentação 4: "apresentacao/apresentacao04.md"
        - Apresentação 5.1: "apresentacao/apresentacao05.1.md"
        - Apresentação 6: "apresentacao/apresentacao06.md"

    - Atas: 
        - Ata 01: "atas/Ata1-24.03.2024.md"
        - Ata 02: "atas/Ata2-31.03.2024.md"
        - Ata 03: "atas/Ata3-07.04.2024.md"
        - Ata 04: "atas/Ata4-05.05.2024.md"
        - Ata 05: "atas/Ata5-02.06.2024.md"
    
    - Planejamento:
        - Termo de Abertura de Projeto: "planejamento/tap.md"
        - EAP: "planejamento/EAP.md"
        - Cronograma Planejado: "planejamento/cronograma_planejado.md"
        - Cronograma Executado: "planejamento/cronograma_executado.md"
        - Heatmap: "planejamento/heatmap.md"
        - Aplicativo escolhido: "planejamento/aplicativo_avaliados.md"
        - Termos de uso: "planejamento/copia_termo_de_uso.md"
        - Ferramentas: "planejamento/ferramentas.md"
        - Metodologia: "planejamento/metodologia.md"
    
    - Pré-Rastreabilidade: 
        - Rich Picture: "pre-rastreabilidade/rich_picture.md"
    
    - Elicitação:
        - Perfil de Usuário: "elicitacao/perfil_de_Usuario.md"
        - Personas: "elicitacao/personas.md"
        - Técnicas de Elicitação:
          - Brainstorming: "elicitacao/brainStorm.md"
          - Introspecção: "elicitacao/Introspeccao.md"
          - Entrevista: "elicitacao/entrevista.md"
          - Questionário: "elicitacao/questionario.md"
          - Storytelling: "elicitacao/storytelling.md"
        - Técnicas de Priorização:
          - Three level scale: "elicitacao/Priorização/threelevelscale.md"
          - 100$: "elicitacao/Priorização/100$.md"
          - First Things First: "elicitacao/Priorização/first_things.md"
        - Requisitos Elicitados: "elicitacao/requisitosElicitados.md"

    - Modelagem:
        - Especificação Suplementar: "modelagem/specSuplementar.md"
        - Casos de Uso: "modelagem/useCase.md"
        - Cenários: "modelagem/cenarios.md"
        - Léxicos: "modelagem/lexicos.md"
        - Validação dos casos de uso: "modelagem/validusecase.md"
        - Ágil:
          - Backlog: "modelagem/Agil/backlog.md"
          - Histórias de Usuário: "modelagem/Agil/historia_de_usuario.md"
          - NFR Framework: "modelagem/Agil/nfr2.md"

    - Verificação e Validação:
        - Preparação:
          - Rich Picture: "verificacao/preparacao/RichPicture.md"
          - Perfil de Usuário: "verificacao/preparacao/PerfildeUsuario.md"
          - Personas: "verificacao/preparacao/Persona.md"
          - Brainstorm: "verificacao/preparacao/Brainstorm.md"
          - Entrevista: "verificacao/preparacao/Entrevista.md"
          - Introspecção: "verificacao/preparacao/Introspeccao.md"
          - Questionário: "verificacao/preparacao/Questionario.md"
          - Análise de documentação: "verificacao/preparacao/AnalisedeDoc.md"
          - Storytelling: "verificacao/preparacao/Storytteling.md"
          - First Things First: "verificacao/preparacao/FirstThings.md"
          - In or Out: "verificacao/preparacao/InOrOut.md"
          - Diagrama de casos de uso: "verificacao/preparacao/CasosDeUsos.md"
          - Especificação Suplementar: "verificacao/preparacao/EspecSuplementar.md"
          - Léxicos: "verificacao/preparacao/Lexicos.md"
          - Cenários: "verificacao/preparacao/Cenarios.md"
          - Backlog: "verificacao/preparacao/Backlog.md"
          - Histórias de usuários: "verificacao/preparacao/HistoriasdeUser.md"
          - NFR Framework: "verificacao/preparacao/NFR.md"
          - Three Level Scale: "verificacao/preparacao/ThreeLevelScale.md"
          - Matriz de rastreabilidade: "verificacao/preparacao/Matriz.md"
        - Inspeções:
          - Grupo 8:
            - Entrega 1: "verificacao/inspecoes/grupo8/entrega1.md"
            - Entrega 2: "verificacao/inspecoes/grupo8/entrega2.md"
            - Entrega 3: "verificacao/inspecoes/grupo8/entrega3.md"
            - Entrega 4: "verificacao/inspecoes/grupo8/entrega4.md"
          - Grupo 7:
            - Entrega 1: "verificacao/inspecoes/grupo7/entrega1.md"
            - Entrega 2: "verificacao/inspecoes/grupo7/entrega2.md"
            - Entrega 3: "verificacao/inspecoes/grupo7/entrega3.md"
            - Entrega 4: "verificacao/inspecoes/grupo7/entrega4.md"
            - Entrega 5: "verificacao/inspecoes/grupo7/entrega5.md" 
        - Validação:
            - Prototipação: "verificacao/validacao/prototipo.md"

    - Rastreabilidade:
      - Elos: "rastreabilidade/Elos.md"
      - Matriz de Rastreabilidade: "rastreabilidade/matriz.md"



theme:
  language: pt-BR
  name: material
  logo: imagens/inss-logo.png
  features:
    - navigation.tabs
    - navigation.top
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/eye
        name: Mudar para o modo escuro

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/eye-outline
        name: Mudar para o modo claro
