repo_url: https://github.com/Requisitos-de-Software/2024.1-Meu-INSS
repo_name: 2024.1-Meu-INSS
site_url: https://github.com/Requisitos-de-Software/2024.1-Meu-INSS

site_name: Meu INSS
nav:
    - Início: "index.md"
    - Apresentação: 
        - Apresentação 1: "apresentacao/apresentacao01.md"
    - Atas: 
        - Ata 01: "atas/Ata1-24.03.2024.md"
        - Ata 02: "atas/Ata2-31.03.2024.md"
        - Ata 03: "atas/Ata3-07.04.2024.md"
    - Planejamento:
        - Termo de Abertura de Projeto: "planejamento/tap.md"
        - EAP: "planejamento/EAP.md"
        - Cronograma Planejado: "planejamento/cronograma_planejado.md"
        - Cronograma Executado: "planejamento/cronograma_executado.md"
        - Heatmap: "planejamento/heatmap.md"
        - Aplicativo escolhido: "planejamento/aplicativo_avaliados.md"
        - Termos de uso: "planejamento/copia_termo_de_uso.md"
        - Ferramentas: "planejamento/ferramentas.md"
    - Pré-Rastreabilidade: 
        - Rich Picture: "pre-rastreabilidade/rich_picture.md"
    - Elicitação:
        - Personas: "elicitacao/personas.md"
        - Brainstorm: "elicitacao/brainStorm.md"
        - Entrevisa: "elicitacao/entrevista.md"

    
theme:
  name: material
  logo: imagens/inss-logo.png
  features:
    - navigation.tabs
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/eye
        name: Mudar para o modo escuro

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/eye-outline
        name: Mudar para o modo claro
